### PR TITLE
Fix code coverage issue

### LINKED ISSUE #1249: Broken coverage reports for common and controller tests
Since upgrade to platformio 6.0 (#1224 which unblocked unit tests - see #1226), coverage reports on codecov are empty for common and controller unit tests.

**Starting points**
See https://community.platformio.org/t/code-coverage-issue-on-native/28126/12 as well as `gcov` documentation: https://gcc.gnu.org/onlinedocs/gcc/Gcov.html

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

### PR DESCRIPTION
**Pull request by asmodai27**
# Description

Upgrade to development version of `platformio` (version `6.1.0rc1`) in order to fix coverage reports.
With that fix, coverage reports are properly generated locally and should work on CI as well.

Closes #1249

## Self-review checklist:

- [x] Self-review: looked through the `Files changed` tab, browsed repository in branch
- [x] Documentation updated - reflects changes in code, electrical or mechanical design
- [x] Documentation and graphics follow the [documentation style guide](https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide)
- [x] New content is linked, easily discoverable, does not require too many clicks
- [x] Follows other relevant parts of [contributor wiki](https://github.com/RespiraWorks/Ventilator/wiki)
- [x] PR has a descriptive name
- [x] Tagged relevant reviewers

### Software only:

- [x] Follows our [code style](https://github.com/RespiraWorks/Ventilator/wiki/Code-style)
- [x] Commented code, particularly in hard-to-understand areas
- [x] All tests pass - new and old, locally and on CI
- [x] No new warnings or static check failures
- [x] Tests that prove fix is effective or new feature works
- [ ] Manual tests are explained, with instructions for reproducing them

### CODE REVIEW

File: software/common/common.sh [hunk 1]
```diff
@@ -110,11 +110,21 @@ install_linux() {
   pip3 install -U pip
   pip3 install codecov
   pip3 install platformio==${PIO_VERSION}
+
+  # upgrading platformio to development version to get proper code coverage reports
+  # remove this when platformio 6.1.0 goes live.
```
Comment (martukas) [inline software/common/common.sh:115]: maybe add a `TODO` here, so it's easy to search for

File: software/controller/platformio.ini [hunk 2]
```diff
@@ -131,4 +130,4 @@ build_flags =
   ${env.build_flags} -g --coverage -lgcov
 extra_scripts =
   platformio/build_config/platformio_sanitizers.py
-build_src_filter = +<src/>
+build_src_filter = +<release/>
```
Comment (martukas) [inline software/controller/platformio.ini:133]: but never `debug`?

**Review by martukas — APPROVED** [review]
LGTM, other than the small suggestions

File: software/controller/platformio.ini (hunk 2 above)
Comment (asmodai27) [reply software/controller/platformio.ini:133]: whoops, that should not be here, it is a leftover from an investigation to the integration test problem...

File: software/common/common.sh (hunk 1 above)
Comment (asmodai27) [reply software/common/common.sh:115]: Absolutely
